name: Push workflow

on: [push]

jobs:
  integration-test-and-ami:
    runs-on: ubuntu-latest

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
          unzip -o packer_1.7.3_linux_amd64.zip -d /usr/local/bin
          rm packer_1.7.3_linux_amd64.zip
  
      - name: Build with Maven
        run: |
          mvn clean install -DskipTests
        working-directory: ${{ github.workspace }}
        

      - name: Print Workspace Contents without artifact
        run: |
          ls -R ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-java-artifact
          path: ${{ github.workspace }}/target/*.jar

      - name: Print Uploaded Artifact Location
        run: |
          echo "Contents of the workspace:"
          ls -R ${{ github.workspace }}

      - name: Packer Init
        run: |
            packer init packer

      - name: Print Contents of Artifact Directory
        run: |
            ls -R ${{ github.workspace }}/target/

      - name: Copy Artifact to Packer
        run: |
          cp -r ${{ github.workspace }}/target/*.jar ${{ github.workspace }}/packer/
          
      - name: Print Contents of Packer
        run: |
          ls -R ${{ github.workspace }}/packer/

      - name: Packer Format
        run: |
          packer fmt -check .

      - name: Build AMI with Packer
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          packer build packer/*.pkr.hcl

      - name: Check Previous Step Status
        run: exit 1
        if: ${{ failure() }}